skanaar/nomnoml

- nomnoml.app.js
Using the more robust method of encoding the url as found on at
http://meyerweb.com/eric/tools/dencoder/ the urls produced are more easily
used in certain places, some markdown parsers for example don't like urls
that aren't encoded heavily.
> Enhance encoding of the shareable link

- bower.json
Tiny json syntax fix.
Fixes [bower](http://bower.io/) so it doesn't exit with an error.
> Fix bower.json, broken json

- nomnoml.renderer.js
The old code only found the intersection within 1% accuracy which lead to some minor line-bleed in some cases.  Replacement code is more accurate and produces cleaner graphics.
Example demonstrating bleed (into `a` and `b` rectangles):
```
#fill: rgba(0,0,0,0)
#zoom: 4
#direction: right
#edgeMargin: 0
#spacing: 77
[a]-[b]
[b]-[c]
```
> Improve precision of rectIntersection

- dist/nomnoml.js
- nomnoml.js
- package.json
- skanaar.svg.js
This ensures the SVG takes up the appropriate horizontal and vertical space within a document.
---
An existing test appears to be failing (and was before this change).
> renderSVG now sets width/height based on the measurer.

- README.md
- dist/nomnoml.js
- index.html
- nomnoml.jison.js
- nomnoml.visuals.js
This change adds a new "transceiver" visual combining "receiver" and "sender" in one stereotype.
Also it makes all three messaging visuals a bit more visually pleasing:
* the receiver's "wedge" is placed on the left (like the corresponding transciever's left edge) for uniformity and visual flow
* wedges are more moderate and do not cause visual off-balance
> Adds a "transceiver" visual combining "receiver" and "sender" in one stereotype

- dist/nomnoml.js
- nomnoml.jison.js
- nomnoml.renderer.js
- test/label-placement.usecase.html
This change improves an association label placement algorithm, avoiding overlapping with connecting blocks and with own association lines. See ./test/label-placement.usecase.html for a usecase. Should fix an issue #28 
Also added possibility to create multi-line association labels, using backticks (`) as line delimiters.
> Improved label placement and multiline labels

- dist/nomnoml.js
- nomnoml.jison.js
- nomnoml.js
- nomnoml.layouter.js
Global direction may cause too long or too tall diagrams, especially when they contain subdiagrams. This change allows to define a local direction in classifier styles, for example:
```
#direction: right
#.vertical: direction=down
#.horizontal: direction=right
[Main|
[<vertical>Left|
[<horizontal>Top] <-> [<horizontal>Bottom]
]
[<vertical>Right|
[<horizontal>Top] <-> [<horizontal>Bottom]
]
[Left] <-> [Right]
]
```
> Allows to set direction in classifiers, independent of a global chart direction

- dist/nomnoml.js
- nomnoml.jison.js
- package-lock.json
- skanaar.svg.js
- test/standalone.svg.usecase.html
I've added html escaping of the text (using lodash escape) to support generics Class<T> in the svg export. Before this broke the svg because of the angle brackets.
I've further added the viewbox attribute to support scaling of the svg by overriding the width and the height.
I've checked all the tests and they all still work except for the requirejs usecase, but that usecase also doesn't work (dagre can't be found) before my changes.
> Added html escaping of the text and a viewbox attribute to the svg export

- src/skanaar.svg.js
This PR revises `SVG.fillText` to accommodate italic text and non-bold text in SVG `<text>` elements.
> Support SVG italic and non-bold text

- src/renderer.js
- src/skanaar.canvas.js
- src/skanaar.svg.js
This PR amends `nomnoml` SVG output and adds a `stroke-dasharray` attribute when the input calls for a "dashed" element.
> Support SVG dashed lines

- src/skanaar.svg.js
This is a follow up to PR #84. It adds a default `dashArray: 'none'` to the SVG `initialState`. Without the default, I found that some SVG paths were rendered with `stroke-dasharray:undefined`. With this PR, they get the proper specification, `stroke-dasharray:none`.
> Set a dash array default

- src/skanaar.svg.js
This PR modifies the `svg.ellipse()` method so that it can draw not only a full ellipse but also the bottom half of an ellipse. This corrects the rendering of a `<database>` node in SVG.
> Support SVG half ellipse

- src/nomnoml.js
- src/renderer.js
- src/skanaar.svg.js
- test/index.html
This PR aims to improve SVG node sizing when possible, by improving the accuracy of the SVG `measureText` method.  The function `renderSvg(code, canvas)`  now has an optional parameter `canvas`.
The pre-existing `measureText` heuristic is still in place and it is the default method. `measureText` will instead use a CanvasRenderingContext2D to measure the text in a particular node only if three conditions are met:
1. `renderSvg` is called from a browser, not from node.js.
2. A canvas element is passed in the second, optional argument to `renderSvg()`.
3. The node uses one of the following fonts: Helvetica, Arial, Times, or Times New Roman.
Helvetica and Arial are font-metric identical. Ditto Times and Times New Roman. They can be safely measured without worry that a user-agent will not …
> Improve SVG measureText

- build.js
- dist/nomnoml.js
- src/jison-parser.js
It can mess such bundler as webpack, which will try to load modules 
[dist/nomnoml.js#L1092](https://github.com/skanaar/nomnoml/compare/master...strobox:master#diff-2ffcfda022e4c4d199e7da4ac55aa2a0L1092)
`var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");`
which exists only in Node.js envirement, not in browser.
> Prevent CommonJS exports in generated jison-parser.js

- src/app.js
This means users can still pan and scale the canvas when their current
code has errors.
> When new code results in parsing error, render last successful code.

- dist/nomnoml.js
- src/domain.ts
- src/layouter.ts
- src/parser.ts
These options seem to affect my diagrams a lot, I know my use case might not be that common, but I thought it had no downsides, so I took the freedom and forked, here's the difference.
I still need to find where the documentation is, so I can update that too if you'd  like.
all we need to add to see those dramatic differences is:
```
#ranker: network-simplex
#acyclicer: greedy
```
> config: add acyclicer and ranker options to directives

- package-lock.json
- package.json
Ran into issues getting a local build working. Tracked it down to two issues:
1. `typescript` not installed as a dev dependency
1. the `webapp` script `cd`s into the `webapp` folder to run `tsc`, but then doesn't `cd..` back out to run the `uglify` step from the root. Fixed that.
> Added typescript as a dev dep and fixed the webapp script

- package.json
Remove duplicate npm scripts, use tsc --build instruction to specify project to build and fix the error(cannot find dist/webapp.js file) when execute webapp script.
> Combine npm scripts and fix minify error when first build

- dist/nomnoml.js
- index.html
- src/nomnoml.ts
- src/skanaar.svg.ts
- test/import-test.nomnoml
- webapp/App.ts
The goal of this PR is to enable the ability to store the nomnoml code within a generated SVG. 
- Embed the escaped source into the `<desc>` tag of the generated SVG
- Add an upload SVG button onto the Webapp and parse out the embedded source
- Enable drag-and-drop onto the editor to easily upload SVGs
The code can probably be moved around into better places, but it's working.
> Embed source into SVG

- src/terminators.ts
Fixes the issue where the composition diamond isn't filled in when exporting to SVG.
Seems to work now. Composition diamond is now filled; aggregation diamond is unfilled (as it should be).
> Fix issue #170

- index.html
This PR fixes a tiny typo in the `og:description` (supercharge you -> supercharge your) so that people don't need to point it out when the link is shared 👁️
> fix: fix typo in the og:description

- dist/nomnoml.js
- src/nomnoml.ts
I took the advice of @kc97ble, and used `path.basename` to get the correct filename.  You should be able to close all of the following after accepting this.
- #164 
- #217 
- #222
> Use path.basename to get the correct filename
